config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get 'answers/edit'
  # get 'questions/index'
  # get 'questions/show'
  # get 'questions/new'
  # get 'questions/edit'
  root "questions#index"
  resources :questions do
    resource :user, only: [:new, :show]
    resources :answers
  end

  # For details
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :content, presence: true
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  
  validates :name, presence: true
  validates :title, presence: true
  validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    if @answer.update(answer_params)
      redirect_to question_path(@question),notice: "回答完了"
    else
      redirect_to question_path(@question),alert: "失敗"
    end
  end


  def edit
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    if @answer.update(answer_params)
      redirect_to question_path(@question), notice: "更新完了"
    else
      flash[:alert] = "エラー"
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question), notice: "削除"
  end



  private
    def answer_params
      params.require(:answer).permit(:content, :name, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    # @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path, notice: "しつもんありがとう！まっててね！"
    else
      flash[:alert] = "エラー"
      render :new
    end
  end

  def edit
    # @question = Question.find(params[:id])
  end

  def update
    # @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to root_path, notice: "編集しました！！"
    else
      flash[:alert] = "エラー"
      render :edit
    end
  end

  def destroy
    # @question = Question.find(params[:id])
    @question.destroy
    redirect_to root_path, notice: "削除しました！"
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end


  def question_params
    params.require(:question).permit(:name, :title, :content)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path, notice: "ログイン完了"
    else
      flash.now[:alert] = "nameもしくはpasswordが異なります"
      render :show
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/edit.html.erb
<div>
  <h2>更新した回答</h2>
  <%= form_with model:[@question, @answer], local: true do |f| %>
    <div class="form-group">
      <div class="form-group">
        <label>なまえ</label>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <label>へんじ</label>
        <%= f.text_area :content, class: "form-control" %>
      </div>
      <div class="text-center">
        <%= f.submit "Update", class: "btn btn-primary" %>
      </div>

    </div>
  <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ultraapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
      <p class="text-success"><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:alert] %>
      <p class="text-danger"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: @question, local:true do |f| %>
  <div class="form-group">
    <label>おなまえ</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>だれにききたい？？</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>ききたいこと！</label>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="text-center">
    <%= f.submit "きいてみる！", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div>
  <div class="col-md-4 offset-md-4">
    <h2 class="text-center">内容を変更！！</h2>
    <%= render "form" %>
  </div>
</div>

app/views/questions/index.html.erb
<h1>ウルトラマンにきいてみよう</h1>
<h2>☆みんなからの質問☆</h2>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead class="thead-light">
        <tr>
          <th>ID</th>
          <th>タイトル</th>
          <th>メニュー</th>
        </tr>
      </thead>
      <tbody>
        <% @questions.each do |question|%>
        <tr>
          <td><%= question.id%></td>
          <td><%= link_to question.title, question_path(question) %></td>
          <td>[<%= link_to "編集する", edit_question_path(question)%>][<%= link_to "削除する", question_path(question), method: :delete, data:{ confirm: "削除してよろしいですか？"}%>]</td>
        </tr>
        <%end%>
      </tbody>
    </table>
    <div>
      <%= link_to "新しく質問する！",new_question_path %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div>
  <div class="col-md-4 offset-md-4">
    <h2 class="text-center">新しい質問！！</h2>
    <%= render "form" %>

  </div>

</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2><%= @question.title %></h2>
     <div>
       質問内容: <%= @question.content %>
     </div>
     <div>
       名前: <%= @question.name %>
     </div>
     <hr>

     <div class="">
       <h3>おへんじ！</h3>
       <table class="table table-striped">
         <% if @question.answers.any? %>
            <thead class="thead-light">
              <tr>
                <td>へんじ</td>
                <td>なまえ</td>
                <td>めにゅー</td>
              </tr>
            </thead>
            <tbody>
              <% @question.answers.each do |answer| %>
                <tr>
                  <td>
                    <%= answer.content %>
                  </td>
                  <td>
                    <%= answer.name %>
                  </td>
                  <td>
                    [<%= link_to "編集", edit_question_answer_path(@question, answer) %>]
                    [<%= link_to "削除", question_answer_path(@question, answer),
                    method: :delete, data:{ confirm: "削除してよろしいですか？"} %>]
                  </td>
                </tr>
              <% end %>
            </tbody>
         <% else %>
          <p>まっててね！</p>
         <% end %>
       </table>
     </div>




     <div>
       <%= link_to "⇨ホームへ⇦" , root_path %>
     </div>

     <div>
       <%= link_to "スタッフログイン" , root_path %>
     </div>

  </div>
</div>

app/views/session/new.html.erb
<h2>スタッフログイン</h2>
<%= form_for(:session, url: login_path) do |f| %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Log in"%>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>